"use client";

import React from "react";
import { ForensicReport } from "../../types/forensic";
import { X, Download, FileText, CheckCircle, AlertTriangle, Calculator, Layers } from "lucide-react";

interface ForensicReportModalProps {
  report: ForensicReport;
  isOpen: boolean;
  onClose: () => void;
}

export const ForensicReportModal: React.FC<ForensicReportModalProps> = ({
  report,
  isOpen,
  onClose,
}) => {
  if (!isOpen) return null;

  const contentAnalysis = report.content_analysis;
  const checks = contentAnalysis?.checks || [];
  const extractedSubjects = contentAnalysis?.extracted_fields?.subjects || [];

  const handleDownloadReport = () => {
    const reportText = `======================================================================
DOCFORENSICS AI - COMPREHENSIVE DOCUMENT FORENSIC REPORT
======================================================================
Document File:   ${report.filename}
Session ID:      ${report.session_id}
Date & Time:     ${report.timestamp_utc}
Final Verdict:   ${report.analysis_status.replace(/_/g, " ").toUpperCase()}

----------------------------------------------------------------------
EXECUTIVE SUMMARY:
----------------------------------------------------------------------
${report.assessment_summary}

----------------------------------------------------------------------
LAYER 1: VISUAL FORENSIC ANALYSIS (PIXEL & SRM NOISE)
----------------------------------------------------------------------
- Model Architecture:      ${report.model_architecture}
- Highest Tampering Score: ${(report.highest_tampering_score * 100).toFixed(1)}%
- Flagged Regions Count:   ${report.suspicious_region_count}
- Flagged Area Coverage:   ${report.total_suspicious_area_percent.toFixed(2)}% of document

${report.suspicious_regions.length === 0 ? "No suspicious pixel-level areas detected." : report.suspicious_regions.map((r) => `
[Area #${r.region_id}]
- Type:                  ${r.region_type.replace(/_/g, " ")}
- Tampering Probability: ${(r.max_tampering_score * 100).toFixed(1)}%
- Document Coverage:     ${r.percentage_of_document_area.toFixed(2)}%
- Extracted Text:        ${r.has_associated_text && r.ocr_text ? `"${r.ocr_text}"` : "None detected"}
- Text Confidence:       ${r.has_associated_text && r.ocr_confidence !== null ? `${(r.ocr_confidence * 100).toFixed(1)}%` : "N/A"}
`).join("")}

----------------------------------------------------------------------
LAYER 2: CONTENT CONSISTENCY & MATHEMATICAL ANALYSIS
----------------------------------------------------------------------
- Document Category: ${contentAnalysis?.document_type || "generic_document"}
- Consistency Status: ${contentAnalysis?.status || "insufficient_information"}
- Summary: ${contentAnalysis?.summary || "N/A"}

${checks.length === 0 ? "No deterministic checks executed." : checks.map((c) => `
[Check: ${c.check_name}]
- Status:     ${c.status.toUpperCase()}
- Displayed:  ${c.displayed_value || "—"}
- Calculated: ${c.calculated_value || "—"}
- Detail:     ${c.explanation}
`).join("")}

${extractedSubjects.length > 0 ? `
Extracted Course Table:
${extractedSubjects.map((s: any, i: number) => `  ${i + 1}. Code/Name: ${s.code || s.name || "Subject"} | Credit: ${s.credits ?? "—"} | Grade: ${s.grade ?? "—"} | GP: ${s.grade_point ?? "—"}`).join("\n")}
` : ""}

----------------------------------------------------------------------
LAYER 3: AUTHORITATIVE RECORD VERIFICATION
----------------------------------------------------------------------
- Status:  ${report.record_verification?.status || "not_available"}
- Source:  ${report.record_verification?.source || "Local System"}
- Message: ${report.record_verification?.message || "No external database configured."}

======================================================================
Generated by DocForensics AI Verification Suite
`;

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `docforensics_report_${report.session_id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* Modal Header */}
        <div className="p-5 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-slate-900 text-white flex items-center justify-center shadow-sm">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-bold text-lg text-slate-900">
                Document Forensic Report
              </h2>
              <p className="font-mono text-xs text-slate-500">
                {report.filename} &bull; ID: {report.session_id.slice(0, 8)}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-200 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          <div className="space-y-6 text-sm text-slate-700">
            {/* Executive Summary Card */}
            <div className="p-5 rounded-xl border border-slate-200 bg-slate-50">
              <h3 className="font-bold text-xs text-slate-500 uppercase tracking-wider mb-2">
                Executive Assessment
              </h3>
              <p className="text-base font-semibold text-slate-900 leading-relaxed mb-4">
                {report.assessment_summary}
              </p>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t border-slate-200 text-xs">
                <div>
                  <span className="text-slate-400 block mb-0.5">Document File</span>
                  <strong className="text-slate-900">{report.filename}</strong>
                </div>
                <div>
                  <span className="text-slate-400 block mb-0.5">Verdict</span>
                  <strong className="text-slate-900 uppercase">
                    {report.analysis_status.replace(/_/g, " ")}
                  </strong>
                </div>
                <div>
                  <span className="text-slate-400 block mb-0.5">Tampering Confidence</span>
                  <strong className="text-red-700 font-mono text-sm">
                    {(report.highest_tampering_score * 100).toFixed(1)}%
                  </strong>
                </div>
                <div>
                  <span className="text-slate-400 block mb-0.5">Analysis Time</span>
                  <strong className="text-slate-900 font-mono">
                    {(report.performance_latency.total_pipeline_latency_ms / 1000).toFixed(2)}s
                  </strong>
                </div>
              </div>
            </div>

            {/* Layer 1: Suspicious Regions Table */}
            <div>
              <div className="flex items-center gap-2 mb-3">
                <Layers className="w-4 h-4 text-blue-600" />
                <h3 className="font-bold text-xs text-slate-700 uppercase tracking-wider">
                  Visual Forensic Analysis ({report.suspicious_regions.length} Flagged Areas)
                </h3>
              </div>

              {report.suspicious_regions.length === 0 ? (
                <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-950 text-xs flex items-center gap-3">
                  <CheckCircle className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>No localized visual manipulation evidence was detected on this document.</span>
                </div>
              ) : (
                <div className="border border-slate-200 rounded-xl overflow-hidden shadow-sm">
                  <table className="w-full text-left border-collapse text-xs">
                    <thead>
                      <tr className="bg-slate-100 border-b border-slate-200 text-slate-700 font-bold">
                        <th className="p-3">Area ID</th>
                        <th className="p-3">Type</th>
                        <th className="p-3">Tampering Probability</th>
                        <th className="p-3">Coverage</th>
                        <th className="p-3">Extracted Text</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-200 font-mono">
                      {report.suspicious_regions.map((r) => (
                        <tr key={r.region_id} className="hover:bg-slate-50">
                          <td className="p-3 font-bold">Area #{r.region_id}</td>
                          <td className="p-3 font-sans capitalize">{r.region_type.replace(/_/g, " ")}</td>
                          <td className="p-3 text-red-700 font-bold">
                            {(r.max_tampering_score * 100).toFixed(1)}%
                          </td>
                          <td className="p-3">{r.percentage_of_document_area.toFixed(2)}%</td>
                          <td className="p-3 font-sans font-bold text-slate-900">
                            {r.has_associated_text && r.ocr_text ? `"${r.ocr_text}"` : "—"}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

            {/* Layer 2: Content Consistency Table */}
            {checks.length > 0 && (
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Calculator className="w-4 h-4 text-blue-600" />
                  <h3 className="font-bold text-xs text-slate-700 uppercase tracking-wider">
                    Content Consistency &amp; Mathematical Verification ({checks.length} Checks)
                  </h3>
                </div>

                <div className="border border-slate-200 rounded-xl overflow-hidden shadow-sm">
                  <table className="w-full text-left border-collapse text-xs">
                    <thead>
                      <tr className="bg-slate-100 border-b border-slate-200 text-slate-700 font-bold">
                        <th className="p-3">Check Rule</th>
                        <th className="p-3">Status</th>
                        <th className="p-3">Displayed</th>
                        <th className="p-3">Calculated</th>
                        <th className="p-3">Explanation</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-200 font-mono text-xs">
                      {checks.map((c) => (
                        <tr key={c.check_id} className="hover:bg-slate-50">
                          <td className="p-3 font-sans font-bold text-slate-900">{c.check_name}</td>
                          <td className="p-3">
                            <span
                              className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                                c.status === "match"
                                  ? "bg-emerald-100 text-emerald-800"
                                  : c.status === "impossible_value"
                                  ? "bg-purple-100 text-purple-800"
                                  : "bg-red-100 text-red-800"
                              }`}
                            >
                              {c.status.toUpperCase()}
                            </span>
                          </td>
                          <td className="p-3 font-bold text-slate-800">{c.displayed_value || "—"}</td>
                          <td className="p-3 font-bold text-slate-800">{c.calculated_value || "—"}</td>
                          <td className="p-3 font-sans text-slate-600">{c.explanation}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Notice */}
            <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 text-xs text-slate-500">
              <strong className="text-slate-700">Notice:</strong> Results indicate statistical visual manipulation patterns and rule-based consistency checks. For official legal proceedings, corroborating manual analysis is recommended.
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 sm:p-5 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="text-xs text-slate-500 hidden sm:block">
            DocForensics AI Verification Report
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleDownloadReport}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-xs font-semibold bg-slate-900 text-white hover:bg-slate-800 transition-colors shadow-sm"
            >
              <Download className="w-4 h-4" />
              <span>Download Report</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
